import React from "react";
import {SidebarProvider, SidebarTrigger} from "@/components/ui/sidebar";
import {PageContent} from "@/components/page";
import RecordSidebar from "@/app/my-work/page";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function RootLayout({children,}: {children: React.ReactNode;}) {
	return (
		<PageContent className="h-screen overflow-hidden bg-blue-400">
			<SidebarProvider>
				<RecordSidebar/>
				<main>
					<SidebarTrigger />
					{children}
				</main>
			</SidebarProvider>
		</PageContent>
	);
}
