import React from "react";
import './global.css';
import RecordSidebar from "@/app/records/page";
import {SidebarProvider, SidebarTrigger} from "@/components/ui/sidebar";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function RootLayout({children,}: {children: React.ReactNode;}) {
	return (
		<html lang="en">
			<body>
				{children}
			</body>
		</html>
	);
}
