import React from "react";
import {SidebarProvider, SidebarTrigger} from "@/components/ui/sidebar";
import RecordSidebar from "@/app/records/page";

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default function RootLayout({children,}: {children: React.ReactNode;}) {
    return (
        <SidebarProvider>
            <RecordSidebar />
            <main>
                <SidebarTrigger />
                {children}
            </main>
        </SidebarProvider>
    );
}
